name: Deploy MkDocs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs toolchain (no requirements.txt)
        run: |
          python -m pip install --upgrade pip
          pip install "mkdocs==1.6.0" "mkdocs-material==9.5.28"

      - name: Build & Deploy
        run: mkdocs gh-deploy --force
